$source = "D:\Travel.IO"
$destination = "D:\Travel.IO_Shareable.zip"

# Exclude heavy autogenerated folders that shouldn't be shared
$exclude = @(
    "*\node_modules\*",
    "*\venv\*",
    "*\__pycache__\*",
    "*\.git\*",
    "*\.DS_Store",
    "*\package-lock.json"
)

Write-Host "Zipping the project, please wait..."

Compress-Archive -Path "$source\*" -DestinationPath $destination -Update -Force

Write-Host "✅ Created $destination successfully!"
